[build]
target = "x86_64-unknown-none"
rustflags = [
    "-C", "relocation-model=static",
    "-C", "code-model=large",
    "-C", "force-frame-pointers=no",
    "-C", "link-arg=-Tlinker.ld",
]

[unstable]
build-std = ["core", "compiler_builtins", "alloc"]

[net]
# libgit2 внутри cargo падает на SSL (unknown error; class=Ssl), системный git
# работает. Заставляем cargo гонять git приложением - обход сетевого прокси.
git-fetch-with-cli = true
