#!/bin/bash
set -e

PROGRAMS_DIR="programs"
PROGRAMS_RS="src/programs.rs"
KERNEL_ELF="target/x86_64-unknown-none/debug/vitamin_os26"
ISO_DIR="target/os.iso.dir"
ISO="target/os.iso"
IMG="target/os.img"

echo "================================="
echo "Building VitaminOS26..."
echo "================================="

###############################################################################
# 1. Check toolchain
###############################################################################
if ! command -v cargo &> /dev/null; then
    echo "Error: Cargo not found."
    exit 1
fi

TOOLCHAIN="nightly-2022-11-01"

if ! rustup toolchain list | grep -q "$TOOLCHAIN"; then
    echo "Installing $TOOLCHAIN toolchain..."
    rustup toolchain install "$TOOLCHAIN"
fi

if ! rustup component list --toolchain "$TOOLCHAIN" | grep -q "rust-src.*installed"; then
    echo "Installing rust-src for $TOOLCHAIN..."
    rustup component add rust-src --toolchain "$TOOLCHAIN"
fi

if ! command -v nasm &> /dev/null; then
    echo "Error: nasm not found. Install it with: apt install nasm"
    exit 1
fi

if ! command -v grub-mkrescue &> /dev/null; then
    echo "Error: grub-mkrescue not found. Install grub-common and xorriso."
    exit 1
fi

###############################################################################
# 2. Check for GCC (C program compilation)
###############################################################################
CC="gcc"
if ! command -v "$CC" &> /dev/null; then
    echo "Warning: gcc not found. C programs will not be compiled."
    CC=""
fi

###############################################################################
# 3. Compile programs (C and Rust) to flat binaries
###############################################################################
PROGRAM_ENTRIES=""

if [ -n "$CC" ]; then
    echo ""
    echo "Compiling C programs..."

    LDSCRIPT="/tmp/vitamin_ldscript_$$"
    cat > "$LDSCRIPT" << 'ENDLD'
    PHDRS
    {
        all PT_LOAD FLAGS(7);
    }
    SECTIONS
    {
        . = 0x0;
        .text : { *(.text) *(.rodata) *(.data) } :all
        .bss : { *(.bss) } :all
    }
ENDLD
fi

for prog_dir in "$PROGRAMS_DIR"/*/; do
    prog_name=$(basename "$prog_dir")
    c_src="${prog_dir}main.c"
    rs_src="${prog_dir}main.rs"
    bin_file="${prog_dir}${prog_name}.bin"

    if [ -f "$c_src" ]; then
        echo ""
        echo "  Compiling (C): $c_src"
        obj_file="${prog_dir}${prog_name}.o"
        so_file="${prog_dir}${prog_name}.so"

        $CC -m64 -nostdlib -ffreestanding -fno-stack-protector -fPIC -mno-red-zone \
            -c "$c_src" -o "$obj_file" 2>&1

        ld -nostdlib -shared -T "$LDSCRIPT" -e _start \
            -o "$so_file" "$obj_file" 2>&1

        objcopy -O binary "$so_file" "$bin_file" 2>&1

        bss_pad=$(readelf -lW "$so_file" | awk '/LOAD/{memsz=strtonum($6); filesz=strtonum($5); if(memsz>filesz) print memsz-filesz}')
        if [ -n "$bss_pad" ] && [ "$bss_pad" -gt 0 ] 2>/dev/null; then
            dd if=/dev/zero bs=1 count="$bss_pad" status=none >> "$bin_file" 2>&1
        fi

        rm -f "$obj_file" "$so_file"
    elif [ -f "$rs_src" ]; then
        echo ""
        echo "  Compiling (Rust): $rs_src"
        # Пикод-модель: программа исполняется по произвольному адресу (ядро
        # загружает .bin в кучу и прыгает на первый байт), поэтому доступ к
        # .rodata/.text должен быть RIP-relative, а не абсолютным.
        RUSTFLAGS="-C relocation-model=pic -C link-arg=-T$(pwd)/${prog_dir}linker.ld" \
            cargo build -Z build-std=core,compiler_builtins \
            --target x86_64-unknown-none \
            --manifest-path "${prog_dir}Cargo.toml" \
            --release 2>&1

        elf_file="${prog_dir}target/x86_64-unknown-none/release/${prog_name}"
        objcopy -O binary "$elf_file" "$bin_file" 2>&1

        bss_pad=$(readelf -lW "$elf_file" | awk '/LOAD/{memsz=strtonum($6); filesz=strtonum($5); if(memsz>filesz) print memsz-filesz}')
        if [ -n "$bss_pad" ] && [ "$bss_pad" -gt 0 ] 2>/dev/null; then
            dd if=/dev/zero bs=1 count="$bss_pad" status=none >> "$bin_file" 2>&1
        fi
    else
        echo ""
        echo "  Skipping $prog_name (no main.c / main.rs)"
        continue
    fi

    size=$(stat -c%s "$bin_file")
    echo "    -> ${bin_file} (${size} bytes)"

    PROGRAM_ENTRIES="${PROGRAM_ENTRIES}    Program { name: \"${prog_name}\", data: include_bytes!(\"../${prog_dir}${prog_name}.bin\") },
"
done

if [ -n "$CC" ]; then
    rm -f "$LDSCRIPT"
fi

###############################################################################
# 4. Generate src/programs.rs
###############################################################################
echo ""
echo "Generating $PROGRAMS_RS..."

cat > "$PROGRAMS_RS" << 'ENDRS'
// Auto-generated by build.sh -- do not edit manually.
pub struct Program {
    pub name: &'static str,
    pub data: &'static [u8],
}

pub const PROGRAMS: &[Program] = &[
ENDRS

if [ -z "$PROGRAM_ENTRIES" ]; then
    echo "    // No C programs found in $PROGRAMS_DIR" >> "$PROGRAMS_RS"
fi

echo "$PROGRAM_ENTRIES" >> "$PROGRAMS_RS"
echo "];" >> "$PROGRAMS_RS"

###############################################################################
# 5. Build kernel (Rust + NASM)
###############################################################################
echo ""
echo "Running: cargo build"
cargo build

echo ""
echo "Kernel ELF: $KERNEL_ELF"

###############################################################################
# 6. Build GRUB ISO
###############################################################################
echo ""
echo "Building GRUB ISO..."

rm -rf "$ISO_DIR"
mkdir -p "$ISO_DIR/boot/grub"

cp "$KERNEL_ELF" "$ISO_DIR/boot/vitamin_os26.elf"
cp grub.cfg "$ISO_DIR/boot/grub/grub.cfg"

grub-mkrescue -o "$ISO" "$ISO_DIR" 2>&1
rm -rf "$ISO_DIR"

###############################################################################
# 6.5. Create disk image (kept if it already has data!)
###############################################################################
if [ ! -f "$IMG" ]; then
    echo ""
    echo "Creating disk image: $IMG (8M)..."
    truncate -s 8M "$IMG"
fi

echo ""
echo "================================="
echo "Build SUCCESS!"
echo "ISO: $ISO"
echo "Disk: $IMG"
echo "Run: qemu-system-x86_64 -cdrom $ISO -drive file=$IMG,format=raw,if=ide"
echo "================================="
