// Auto-generated by build.sh -- do not edit manually.
pub struct Program {
    pub name: &'static str,
    pub data: &'static [u8],
}

pub const PROGRAMS: &[Program] = &[
    Program { name: "clock", data: include_bytes!("../programs/clock/clock.bin") },
    Program { name: "example", data: include_bytes!("../programs/example/example.bin") },
    Program { name: "fetch", data: include_bytes!("../programs/fetch/fetch.bin") },
    Program { name: "help", data: include_bytes!("../programs/help/help.bin") },
    Program { name: "snake", data: include_bytes!("../programs/snake/snake.bin") },
    Program { name: "vita", data: include_bytes!("../programs/vita/vita.bin") },

];
